#!/bin/bash
sname=`basename $0`
if [ "`echo $0 | cut -c1`" = "/" ]; then
  spath=`dirname $0`
else
  spath=`pwd`/`echo $0 | sed -e s/$sname//`
fi
owner=`ls -l $spath | grep $sname | awk '{print $3}'`
echo "Creating a symbolic link for the cake console at /usr/local/bin/cake, with owner $owner:$owner"
ln -s $spath/cake.php /usr/local/bin/cake
chown $owner:$owner /usr/local/bin/cake
chmod +x /usr/local/bin/cake