#!/bin/bash
opath="/usr/local/bin/cake"
if test -f $opath
then
	echo "A file already exists at $opath, please remove it and re-run this script"
	exit 1
fi
sname=`basename $0`
if [ "`echo $0 | cut -c1`" = "/" ]; then
  spath=`dirname $0`
else
  spath=`pwd`/`echo $0 | sed -e s/$sname//`
fi
owner=`ls -l $spath | grep $sname | awk '{print $3}'`
echo "Creating a symbolic link for the cake console at $opath, with owner $owner:$owner"
if ln -s $spath/cake.php $opath
then
	chown $owner:$owner $opath 
	chmod +x $opath
else
	echo "Failed to create a symbolic link from $spath/cake.php to $opath";
	exit 2
fi
